DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS images;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    country TEXT NOT NULL,
    city TEXT NOT NULL,
    content TEXT NOT NULL,
    start TEXT NOT NULL,
    until TEXT NOT NULL
);

CREATE TABLE tickets (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ticket_id TEXT NOT NULL,
    valid INTEGER NOT NULL
);

CREATE TABLE images (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    code TEXT NOT NULL,
    filename TEXT NOT NULL
);
